# Generated by Django 3.2.7 on 2021-09-21 22:10

from django.db import migrations, models
import ovaas.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('username', models.CharField(max_length=16, unique=True)),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'User',
                'db_table': 'userinfo',
            },
            managers=[
                ('objects', ovaas.models.MyUserManager()),
            ],
        ),
    ]
