# Generated by Django 3.2.7 on 2021-09-14 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ovaas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='UserInfo',
        ),
    ]
