# Generated by Django 3.2.7 on 2021-09-21 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ovaas', '0005_auto_20210921_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
